### ISSUE TITLE
Can the :scalafmt and :checkscalafmt commands utilize gradle cache ?

### ISSUE THREAD

**Issue by ahakanbaba** [alenkacz/gradle-scalafmt#27]
Instead of re-executing scalafmt for files that have not changed, is it possible to utilize the gradle cache and skip the execution ?

**Comment by wugui2020** [comment]
Wondering the same thing. The command can take awhile to run when running against a big project.

**Comment by mieciu** [comment]
I've been also missing this possibility so I've filed a PR https://github.com/alenkacz/gradle-scalafmt/pull/33 today.

Hopefully it gets merged and published soon, there's lot of time to be saved by this 🙂
