### ISSUE TITLE
Use Gradle defined maven repositories to download scalafmt

### ISSUE THREAD

**Issue by nyonson** [alenkacz/gradle-scalafmt#28]
Would it be possible to use the maven repositories defined in a buildscript to download the scalafmt artifact?

It appears to be hard-coded to maven central. This breaks on CI machines probably due to our IP getting rate limited.

Related issue in the scalafmt project: https://github.com/scalameta/scalafmt/issues/1415

**Comment by tomasherman** [comment]
this was blocked for a long time on scalafmt side but it should now be possible (see https://github.com/scalameta/scalafmt/issues/1521)

**Comment by augi** [comment]
Already implemented
